config/routes.rb
PosHomework::Application.routes.draw do
  resources :line_items

  devise_for :users do
    get 'users/signout' => "devise/sessions#destroy"
  end

  resources :users
  resources :products
  resources :orders

  root :to => "home#enter"
  get "home", to: "home#index", as: :home

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :product, :order_id, :product_id
  belongs_to :order
  belongs_to :product

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :user

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)

    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def order_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :price, :intro
  validates :title, :price, :intro, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true

  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line items present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :orders
  has_many :line_items, :through => :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_order
    Order.find(session[:order_id])
  rescue ActiveRecord::RecordNotFound
    order = Order.create
    session[:order_id] = order.id
    order
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.order(:title)
    @order = current_order

    render layout: "order"
  end

  def enter

  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @order = current_order
    product = Product.find(params[:product_id])
    @line_item = @order.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to home_url }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all

    respond_to do |format|
      format.html
      format.json { render json: @orders}
    end
  end

  def show
    begin
      @order = Order.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid order #{params[:id]}"
      redirect_to home_url, notice: "invalid order"
    else
      respond_to do |format|
        format.html
        format.json { render json: @order}
      end
    end
  end

  def new
    @order = Order.new

    respond_to do |format|
      format.html
      format.json { render json: @order}
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was created"}
        format.json { render json: @order, status: :created, locatioin: @order}
      else
        format.html { render :new}
        format.json { render json: @order.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'order is created'}
        format.json { head :no_content}
      else
        format.html { render :edit}
        format.json { render json: @order.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @order = current_order
    @order.destroy
    session[:order_id] = nil

    respond_to do |format|
      format.html { redirect_to home_url, notice: 'You empty your order' }
      format.json { head :ok}
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout "product"
  def index
    @products = Product.all

    respond_to do |format|
      format.html
      format.json { render json: @products}
    end
  end

  def show
    @product = Product.find(params[:id])
    
    respond_to do |format|
      format.html
      format.json { render json: @product}
    end
  end

  def new
    @product = Product.new

    respond_to do |format|
      format.html
      format.json { render json: @product}
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was created"}
        format.json { render json: @product, status: :created, location: @product}
      else
        format.html { render action: new}
        format.json { render json: @product.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was updated'}
        format.json { head :no_content }
      else
        format.html { render action: "edit"}
        format.json { render json: @product.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to product_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/enter.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body id="homepage">
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name"><h1><%= link_to "Pos机网页登录", home_path %></h1></li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider hide-for-small"></li>
          <% if user_signed_in? %>
            <li> <%= link_to current_user.email, user_path(current_user)  %> </li>
            <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </section>
    </nav>
    <body>
      <div class="left"><%= image_tag "er.svg" %> </div>
      <div class="right">
        <pre>
          说明
1.左边是ER图
2.测试系统使用帐号密码
username: test@gmail.com
passwd: test1234

3.网站基于 Rails 框架搭建
4.还是有点简陋，功能会继续完善
        </pre>
        <% if user_signed_in? %>
          <%= link_to "管理", user_path(current_user) , class: "large button" %>
        <% else %>
          <%= button_to "登录", new_user_session_path, class: "large button" %>
        <% end %>
        <%= javascript_include_tag :application %>
      </div>
    </body>
  </body>
</html>

app/views/home/index.html.erb
<% @products.each do |product| %>
  <div class="entry">
    <h3><%= product.title %></h3>
    <%= sanitize(product.intro) %>
    <div class="price_line">
      <span class="price"><%= number_to_currency(product.price) %></span>
      <%= button_to 'Add to Order', line_items_path(product_id: product) %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/order.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body id="show">
    <h2>Product Available </h2>
    <%= yield %>
    <div class="order">
      <%= render @order %>
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/product.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="product">
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<ul>
  <li><%= line_item.product.title %> * <%= line_item.quantity %></li>
  <li><%= number_to_currency line_item.total_price %> </li>
</ul>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<h2>Your order</h2>

<ul>
  <% @order.line_items.each do |item| %>
    <li><%= item.product.title %> </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/orders/_order.html.erb
<h2>Your Order</h2>

<%= render order.line_items %>

<div class="total">
  
  <% if order.vip %>
    You can have a discount
  <% else %>
    You cannot give this order a discount
  <% end %>
  <br>
  Total price is  <%= number_to_currency(order.order_price) %>
</div>

<%= button_to 'Empty the order', order, method: :delete, confirm: "R U sure, babe?" %>
<button><%= link_to "Check it", order_path(order) %> </button>
<button onClick="javascript:window.print();">打印</button>

app/views/orders/show.html.erb
<%= render @order %>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
 <% if @product.errors.any? %>
  <div id="error_explaination">
    <h2><%= pluralize @product.errors.count, "error" %> so the product cannot be saved</h2>

    <ul> 
      <%= @product.errors.full_messages.each do |msg| %>
        <li><%= msg %> </li>
      <% end %>
    </ul>
  </div>
 <% end %>
  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :intro %>
    <%= f.text_area :intro %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h2>edit it </h2>
<%= render 'form' %>

<%= link_to "show", @product %>
<%= link_to "Back", products_path %>

app/views/products/index.html.erb
<h2>index page</h2>
<% @products.each do |product| %>
  <div class="property"> 
    Product: <%= product.title %> </div>
  <div class="property"> 
    Price: <%= product.price %> </div>
  <div class="property"> 
    Descrption: <%= product.intro %> </div>

  <div class="links">
    <%= link_to 'show', product %>
    <%= link_to 'edit', edit_product_path(product) %>
    <%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you Sure , babe?'} %>
  </div>
<% end %>

<div class="new_product">
  <%= link_to "New a product", new_product_path, class: :button %>
  <%= link_to "Back", user_path(current_user), class: :button %>
</div>

app/views/products/new.html.erb
<h1> new a product </h1>

<%= render 'form' %>

<%= link_to "Back", products_path %>

app/views/products/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<%= render @product %>
<%= link_to "Edit", edit_product_path(@product) %>
<%= link_to "Back", products_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="column">
    <%= f.label "name" %>
    <%= f.text_field :name %>
  </div>

  <div class="column">
    <%= f.field "email" %>
    <%= @user.email %>
  </div>

  <div class="column">
    <%= f.field "email" %>
    <%= @user.email %>
  </div>

  <%= f.submit %>

<% end %>

app/views/users/index.html.erb
List all the user now <br>
<% @users.each do |user| %>
 <%= user.email %>
<% end %>

app/views/users/show.html.erb
<p class="user-show">
  your email is <%= current_user.email %>,Start to do something <br>

  <%= link_to "Product management", products_path, class: "button first" %> 
  <%= link_to "User management", users_path, class: :button %> <br>
  <%= link_to "check the Order", home_path, class: :button %>
</p>